-- Create activities table
create table "public"."activities" (
    "id" bigint primary key generated always as identity,
    "user_id" uuid not null references auth.users(id) on delete cascade,
    "title" text not null,
    "description" text not null,
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS (Row Level Security) policies
alter table "public"."activities" enable row level security;

-- Create policy to allow users to only read their own activities
create policy "Users can view own activities"
    on activities for select
    using (auth.uid() = user_id);

-- Create policy to allow system to insert activities
create policy "System can insert activities"
    on activities for insert
    to service_role;


-- Add indexes
create index activities_user_id_idx on activities(user_id);
create index activities_created_at_idx on activities(created_at);

-- Add comments
comment on table activities is 'Table storing user activities generated by the system';
comment on column activities.user_id is 'References the user who owns this activity';
comment on column activities.title is 'Title of the activity';
comment on column activities.description is 'Detailed description of the activity';